# Generated by Django 2.2.4 on 2019-10-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artcraft',
            name='totalNumber',
        ),
        migrations.RemoveField(
            model_name='fun',
            name='totalNumber',
        ),
        migrations.RemoveField(
            model_name='kids',
            name='totalNumber',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='totalNumber',
        ),
        migrations.RemoveField(
            model_name='selfdevelopment',
            name='totalNumber',
        ),
    ]
