# Generated by Django 2.2.4 on 2019-10-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('endtime', models.TimeField()),
                ('image', models.FileField(upload_to='static/')),
                ('currentnum', models.IntegerField(default=0)),
                ('maxnum', models.IntegerField(default=10)),
                ('category', models.TextField()),
                ('emaillist', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
