# Generated by Django 2.2.4 on 2019-10-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('endtime', models.TimeField()),
                ('image', models.FileField(upload_to='static/')),
                ('currentnum', models.IntegerField(default=0)),
                ('maxnum', models.IntegerField(default=10)),
                ('emaillist', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsHosting.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsHosting.Category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsHosting.Event')),
            ],
        ),
    ]
