# Generated by Django 2.2.2 on 2019-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101)),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to='uploads/')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
