# Generated by Django 2.2.2 on 2019-10-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.TextField(default='fun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='currentnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='maxnum',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='static/'),
        ),
    ]
