# Generated by Django 2.2.4 on 2019-10-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='startDateTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='currentnum',
        ),
        migrations.RemoveField(
            model_name='event',
            name='emaillist',
        ),
    ]
