# Generated by Django 2.2.4 on 2019-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0002_auto_20191020_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
