# Generated by Django 2.2.2 on 2019-10-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0002_auto_20191015_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emaillist',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
