# Generated by Django 2.2.4 on 2019-10-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0003_booking_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
    ]
