# Generated by Django 2.2.2 on 2019-10-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0004_auto_20191016_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
