# Generated by Django 2.2.4 on 2019-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0004_remove_booking_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=101)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=101)),
                ('tickets', models.ManyToManyField(to='EventsHosting.TicketType')),
            ],
        ),
    ]
