# Generated by Django 2.2.2 on 2019-10-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0005_auto_20191016_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='emaillist',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(verbose_name=''),
        ),
    ]
