# Generated by Django 2.2.4 on 2019-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0005_eventtickets_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='type',
            field=models.CharField(choices=[('Live', 'Live'), ('Archived', 'Archived')], default='Paid', max_length=50),
        ),
    ]
