# Generated by Django 2.2.2 on 2019-10-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0006_auto_20191016_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='emaillist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(),
        ),
    ]
