# Generated by Django 2.2.2 on 2019-10-16 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EventsHosting', '0007_auto_20191016_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
